### ISSUE TITLE
New docs not live on GitHub Pages

### ISSUE THREAD

**Issue by shailen-naidoo** [learn-vuejs/vue-patterns#25]
Hey, I just cloned the repo to add the new `v-slot` syntax because the new syntax appears not to be live on the `https://learn-vuejs.github.io/vue-patterns/`. Only after checking the cloned repo, i see the new syntax is already there :)

**Comment by simsim0709** [comment]
Thanks, @ShailenNaidoo. It seems like travis ci is broken. I have just deployed new docs.

Thanks again.

**Comment by shailen-naidoo** [comment]
Awesome!
