### ISSUE TITLE
Add Spanish to languages

### ISSUE THREAD

**Issue by ederchrono** [learn-vuejs/vue-patterns#31]
Hi I'd like to contribute translating and adding Spanish to the languages dropdown. 
Is that ok? 
If your answer is yes, how is your git workflow? do you prefer one big PR with everything or should I make a PR per pattern/view?

**Comment by simsim0709** [comment]
Are you still interested in translating it?
Then, one pr is preferred.
Or, maybe you can fork this repo and translate it, and I will add your repo/site link.
It's up to you!
Thanks in advance.

**Comment by simsim0709** [comment]
Thank you for your contribution.
And, sorry for the late merge. 🙏
