### ISSUE TITLE
useful-links has a couple of broken links

### ISSUE THREAD

**Issue by shaftoe** [learn-vuejs/vue-patterns#36]
I haven't gone through each one (yet) but for sure a couple are broken:

- [Edit this page](https://github.com/learn-vuejs/vue-patterns/edit/master/useful-links/README.md) (at the very bottom)
- [An imperative guide to forms in Vue.js](https://blog.logrocket.com/an-imperative-guide-to-forms-in-vue-js-7536bfa374e0)

HTH

**Comment by simsim0709** [comment]
Thank you for reporting the issue. 👍 
I just fixed broken links.
