### ISSUE TITLE
Closing tag

### ISSUE THREAD

**Issue by Parasolio** [learn-vuejs/vue-patterns#6]
For beginners, the difference between opening and closing tags is confusing. `<parent-component></ancestor-component>`

In Dependency Injection:
`
<parent-component>
  <child-component>
    <grand-child-component></grand-child-component>
  </child-component>
</ancestor-component>
`

**Comment by simsim0709** [comment]
Thanks, @Parasolio.

I didn't notice it! 👍

**Comment by Parasolio** [comment]
No problem. You have nice and very useful tutorial.
